---
title: "SGR: Support for Gay Rights"
---

### The Support for Gay Rights (SGR) Database

Support for gay rights has increased in the publics of many countries over recent decades, but the scholarship on the topic has been hindered by the limited available data on these trends in public opinion. The goal of the Support for Gay Rights (SGR) dataset is to overcome this problem. The SGR dataset is constructed by combining a comprehensive collection of survey data with a latent-variable model to provide annual time-series estimates of public support for gay rights across 118 countries and over as many as 51 years that are comparable across space and time. We anticipate that the SGR data will become a crucial source for cross-national, cross-regional, and longitudinal research that improves our understanding of the sources and consequences of public support for gay rights.

A full description of the SGR dataset, the source data used to generate it, and validations of its estimates is presented here:

[Woo, Byung-Deuk](https://www.byung-deuk-woo.org), [Hyein Ko](https://www.heyikon.com), [Yuehong Cassandra Tai](https://cassyuehtai.netlify.app), [Yue Hu](http://www.drhuyue.site), and [Frederick Solt](https://fsolt.org). Forthcoming. ["Public Support for Gay Rights Across Countries and Over Time."](../../publications/published/gayrights) _Social Science Quarterly_.

There are two ways of using the SGR data. To directly compare up to four countries in estimated levels and trends of public gender egalitarianism, use the SGR web app below. To use the SGR in statistical analyses, datasets formatted for use in Stata and R are available for download.

<!-- [<i class="fa-regular fa-compass"></i> Explore the Source Data](pge_faq.html){.btn-custom .btn role="button"} -->


[<i class="fa-solid fa-cloud-arrow-down"></i> Download the SGR](https://doi.org/10.7910/DVN/WF3USY){.btn-custom .btn .btn-lg role="button"} [<i class="fa-solid fa-circle-question"></i> SGR FAQ](sgr_faq/){.btn-custom .btn .btn-lg role="button"}


::: column-page
<iframe src="https://fsolt.shinyapps.io/sgrweb">

</iframe>
:::

Powered by [RStudio](http://shiny.rstudio.com).

Please cite the SGR as follows:

Woo, Byung-Deuk, Hyein Ko, Yuehong Cassandra Tai, Yue Hu, and Frederick Solt. Forthcoming. "Public Support for Gay Rights Across Countries and Over Time." *Social Science Quarterly*. SGR Version 1.0, December 2024.
