project:
  type: website
  output-dir: docs

website:
  title: "DCPO"
  image: "dcpo.png"
  favicon: "favicon.png"
  open-graph: true
  twitter-card:
    site: "@dcpo_lab"
  site-url: https://dcpo.org
  description: "Dynamic Comparative Public Opinion"
  repo-url: https://github.com/fsolt/dcpo_site
  repo-actions: [edit, issue]
  navbar:
    background: "#2849A0"
    logo: dcpo.png
    title: false
    collapse-below: lg
    left:
      - text: "Team"
        href: team/index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Data"
        menu:
          - text: "Public Gender Egalitarianism"
            href: data/pge/index.qmd
          - text: "Democratic Support Dataset"
            href: data/dsd/index.qmd
      - software.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: "bug"
            href: "https://github.com/fsolt/DCPOtools/issues"
          - text: "DCPO Discussions"
            icon: "chat-right-text"
            href: "https://github.com/fsolt/DCPOtools/discussions"
    right:
      - icon: twitter
        href: https://twitter.com/dcpo_lab
      - icon: github
        href: https://github.com/fsolt/DCPOtools

format:
  html:
    theme:
      - cosmo
      - custom.scss
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true


